---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/procfs/disk/* : {}
      config:
        /intel/procfs/disk:
            ignore_loopback: true
            ignore_ram: true
